name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and save the Docker image
      run: docker build -t portfolio.html:latest .
      run: docker save portfolio.html:latest -o portfolio($date).tar
    - uses: actions/upload-artifact@v4
      with:
        name: portfolio.tar
        path: portfolio.tar
