name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag portfolio:$(date +%s)
    - uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: output/test-results.html
